/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'category' : ContactCategory,
}
export type ContactCategory = { 'other' : null } |
  { 'personal' : null } |
  { 'professional' : null } |
  { 'natural' : null };
export interface MeetingNote {
  'id' : bigint,
  'date' : string,
  'summary' : string,
  'contactId' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createContact' : ActorMethod<[string, ContactCategory], bigint>,
  'createMeetingNote' : ActorMethod<[bigint, string, string], bigint>,
  'getContactsByUser' : ActorMethod<[Principal], Array<Contact>>,
  'getContactsByUserAndCategory' : ActorMethod<
    [Principal, ContactCategory],
    Array<Contact>
  >,
  'getMeetingNotesByContact' : ActorMethod<[bigint], Array<MeetingNote>>,
  'login' : ActorMethod<[string], undefined>,
  'summarizeText' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMeetingNote' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];